import { TUNINGS, generateFretboard } from '../theory/fretboard';
import type { Lesson, LessonModule } from './types';
import { createCurriculum } from './curriculum';

export const MODULES: LessonModule[] = [
  {
    id: 'foundations',
    title: 'Module 1 — Foundations',
    description: 'The notes, scales, and the sound of the blues.',
  },
  {
    id: 'form',
    title: 'Module 2 — The 12-Bar Blues',
    description: 'Dominant chords, the blues form, and the shuffle feel.',
  },
  {
    id: 'technique',
    title: 'Module 3 — Fingerpicking Technique',
    description: 'Train your thumb and fingers to pick independently.',
  },
  {
    id: 'together',
    title: 'Module 4 — Putting It Together',
    description: 'Real fingerstyle blues grooves and a full 12-bar chorus.',
  },
];

export const LESSONS: Lesson[] = [
  // ---------------- Module 1: Foundations ----------------
  {
    id: 'l1-strings',
    moduleId: 'foundations',
    title: 'Meet Your Strings',
    category: 'theory',
    summary: 'Learn the names of the four strings and how notes are organized.',
    content: [
      { type: 'paragraph', text: 'A ukulele has four strings. From the one closest to the ceiling (the 4th string) down to the floor, they are tuned G, C, E, A. In Low-G tuning the G string is the lowest-pitched; in standard (re-entrant) tuning it jumps up an octave.' },
      { type: 'heading', text: 'How notes are named' },
      { type: 'paragraph', text: 'The musical alphabet runs A B C D E F G and then repeats. Between most letters there is a sharp/flat note (a half step). Each fret you move up the neck raises the pitch by one half step.' },
      { type: 'tip', text: 'Pluck one string at a time and let it ring. The app listens to a single note at a time, so clean, separate plucks score best.' },
    ],
    practice: [
      {
        id: 'l1-p1',
        title: 'String roll up',
        instructions: 'Pluck the open strings from low to high: G, C, E, A.',
        root: 'C',
        scaleKey: 'ionian',
        positions: [[0, 0], [1, 0], [2, 0], [3, 0]],
        bpm: null,
      },
      {
        id: 'l1-p2',
        title: 'String roll down',
        instructions: 'Now reverse it: pluck A, E, C, G.',
        root: 'C',
        scaleKey: 'ionian',
        positions: [[3, 0], [2, 0], [1, 0], [0, 0]],
        bpm: null,
      },
    ],
    checkpoint: {
      title: 'Play the open strings: G, C, E, A',
      instructions: 'Pluck each open string in order, one at a time, letting each note ring clearly.',
      root: 'C',
      scaleKey: 'ionian',
      positions: [[0, 0], [1, 0], [2, 0], [3, 0]],
      requiredAccuracy: 0.75,
      bpm: null,
    },
  },
  {
    id: 'l2-major-scale',
    moduleId: 'foundations',
    title: 'Half Steps & the Major Scale',
    category: 'theory',
    summary: 'Understand intervals and play your first scale.',
    content: [
      { type: 'paragraph', text: 'A half step is one fret. A whole step is two frets. The major scale is built from a fixed pattern of whole (W) and half (H) steps: W-W-H-W-W-W-H.' },
      { type: 'paragraph', text: 'Starting on C and following that pattern gives C-D-E-F-G-A-B-C — the C major scale, with no sharps or flats. This is the reference every other scale is measured against.' },
      { type: 'list', items: ['1 (C) — the root, home base', '3 (E) — defines major vs minor', '5 (G) — the strong, stable interval', '7 (B) — the leading tone that pulls back home'] },
    ],
    practice: [
      {
        id: 'l2-p1',
        title: 'Lower four notes',
        instructions: 'Play the bottom of the scale: C, D, E, F.',
        root: 'C',
        scaleKey: 'ionian',
        positions: [[1, 0], [1, 2], [2, 0], [2, 1]],
        bpm: null,
      },
      {
        id: 'l2-p2',
        title: 'Upper four notes',
        instructions: 'Play the top of the scale: G, A, B, C.',
        root: 'C',
        scaleKey: 'ionian',
        positions: [[2, 3], [3, 0], [3, 2], [3, 3]],
        bpm: null,
      },
      {
        id: 'l2-p3',
        title: 'Descending C major',
        instructions: 'Come back down the whole scale: C B A G F E D C.',
        root: 'C',
        scaleKey: 'ionian',
        positions: [[3, 3], [3, 2], [3, 0], [2, 3], [2, 1], [2, 0], [1, 2], [1, 0]],
        bpm: null,
      },
    ],
    checkpoint: {
      title: 'Play the C major scale, ascending',
      instructions: 'Climb the C major scale one note at a time: C D E F G A B C.',
      root: 'C',
      scaleKey: 'ionian',
      positions: [[1, 0], [1, 2], [2, 0], [2, 1], [2, 3], [3, 0], [3, 2], [3, 3]],
      requiredAccuracy: 0.8,
      bpm: null,
    },
  },
  {
    id: 'l3-blues-scale',
    moduleId: 'foundations',
    title: 'The Blues Scale & the Blue Note',
    category: 'theory',
    summary: 'Discover the scale at the heart of every blues lick.',
    content: [
      { type: 'paragraph', text: 'The blues scale is a minor pentatonic scale (1, b3, 4, 5, b7) with one extra note added: the b5, known as the "blue note". In C that gives C, Eb, F, Gb, G, Bb.' },
      { type: 'paragraph', text: 'The blue note (Gb here) is dissonant on purpose. Passing through it quickly creates the slippery, vocal, crying quality that defines the blues.' },
      { type: 'tip', text: 'Lean on the b3 (Eb) and b7 (Bb) — these "blue" tones give the scale its mood even before you add the b5.' },
    ],
    practice: [
      {
        id: 'l3-p1',
        title: 'Lower blues notes',
        instructions: 'Play the first four notes including the blue note: C, Eb, F, Gb.',
        root: 'C',
        scaleKey: 'blues',
        positions: [[1, 0], [1, 3], [2, 1], [2, 2]],
        bpm: null,
      },
      {
        id: 'l3-p2',
        title: 'Descending C blues',
        instructions: 'Come down the blues scale: C Bb G Gb F Eb C.',
        root: 'C',
        scaleKey: 'blues',
        positions: [[3, 3], [3, 1], [2, 3], [2, 2], [2, 1], [1, 3], [1, 0]],
        bpm: null,
      },
    ],
    checkpoint: {
      title: 'Play the C blues scale, ascending',
      instructions: 'Climb the C blues scale: C Eb F Gb G Bb C. Notice the tension of the blue note.',
      root: 'C',
      scaleKey: 'blues',
      positions: [[1, 0], [1, 3], [2, 1], [2, 2], [2, 3], [3, 1], [3, 3]],
      requiredAccuracy: 0.8,
      bpm: null,
    },
  },

  // ---------------- Module 2: The 12-Bar Blues ----------------
  {
    id: 'l4-dom7',
    moduleId: 'form',
    title: 'Dominant 7th Chords',
    category: 'theory',
    summary: 'The chord sound that makes music feel bluesy.',
    content: [
      { type: 'paragraph', text: 'A dominant 7th chord is a major triad (1-3-5) plus a flat 7th (b7). C7 is C-E-G-Bb. That b7 adds restless tension that wants to resolve — the core engine of blues harmony.' },
      { type: 'paragraph', text: 'In the blues, every chord is often played as a dominant 7th, even the "home" chord. That is unusual in other styles and is a big part of why the blues sounds the way it does.' },
    ],
    practice: [
      {
        id: 'l4-p1',
        title: 'C major triad',
        instructions: 'Play the plain major triad first: C, E, G.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[1, 0], [2, 0], [2, 3]],
        bpm: null,
      },
      {
        id: 'l4-p2',
        title: 'C7 descending',
        instructions: 'Now add the b7 and come back down: Bb, G, E, C.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[3, 1], [2, 3], [2, 0], [1, 0]],
        bpm: null,
      },
    ],
    checkpoint: {
      title: 'Arpeggiate a C7 chord',
      instructions: 'Pluck the notes of C7 one at a time, low to high: C E G Bb.',
      root: 'C',
      scaleKey: 'mixolydian',
      positions: [[1, 0], [2, 0], [2, 3], [3, 1]],
      requiredAccuracy: 0.8,
      bpm: null,
    },
  },
  {
    id: 'l5-twelve-bar',
    moduleId: 'form',
    title: 'The 12-Bar Blues Form (I–IV–V)',
    category: 'theory',
    summary: 'The most important 12 bars in popular music.',
    content: [
      { type: 'paragraph', text: 'The 12-bar blues is a repeating 12-measure pattern built from three chords: the I (one), IV (four), and V (five). In the key of C those are C7 (I), F7 (IV), and G7 (V).' },
      { type: 'heading', text: 'The classic shape' },
      { type: 'list', items: ['Bars 1-4: I  I  I  I', 'Bars 5-6: IV  IV', 'Bars 7-8: I  I', 'Bar 9: V', 'Bar 10: IV', 'Bars 11-12: I  V (the turnaround)'] },
      { type: 'tip', text: 'Memorize the three root notes first: C, F, G. Everything else hangs off them.' },
    ],
    practice: [
      {
        id: 'l5-p1',
        title: 'I to IV (C ↔ F)',
        instructions: 'Move between the I and IV roots: C, F, C, F.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[1, 0], [2, 1], [1, 0], [2, 1]],
        bpm: null,
      },
      {
        id: 'l5-p2',
        title: 'IV to V (F ↔ G)',
        instructions: 'Move between the IV and V roots: F, G, F, G.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[2, 1], [2, 3], [2, 1], [2, 3]],
        bpm: null,
      },
    ],
    checkpoint: {
      title: 'Play the I–IV–V roots: C, F, G, C',
      instructions: 'Play the root of each chord in the progression: C (I), F (IV), G (V), back to C.',
      root: 'C',
      scaleKey: 'mixolydian',
      positions: [[1, 0], [2, 1], [2, 3], [3, 3]],
      requiredAccuracy: 0.8,
      bpm: null,
    },
  },
  {
    id: 'l6-shuffle',
    moduleId: 'form',
    title: 'The Shuffle Feel',
    category: 'practice',
    summary: 'Trade straight rhythm for the swinging blues groove.',
    content: [
      { type: 'paragraph', text: 'Blues rarely uses even eighth notes. Instead it "shuffles" — each beat is split into a long-short triplet feel (like saying "hum-pty hum-pty"). This swing is what makes the blues groove.' },
      { type: 'paragraph', text: 'Turn on the metronome for this checkpoint. Play your bass notes right on the click and feel the steady pulse before you worry about the swing between beats.' },
    ],
    practice: [
      {
        id: 'l6-p1',
        title: 'Steady C bass',
        instructions: 'Play the C bass note once per click. Lock to the beat.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[1, 0], [1, 0], [1, 0], [1, 0]],
        bpm: 70,
      },
      {
        id: 'l6-p2',
        title: 'Steady G bass',
        instructions: 'Now play the G bass note once per click.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[2, 3], [2, 3], [2, 3], [2, 3]],
        bpm: 70,
      },
    ],
    checkpoint: {
      title: 'Steady bass on the beat (C / G)',
      instructions: 'With the metronome on, alternate the C and G bass notes, one pluck per click. Stay locked to the beat.',
      root: 'C',
      scaleKey: 'mixolydian',
      positions: [[1, 0], [2, 3], [1, 0], [2, 3], [1, 0], [2, 3], [1, 0], [2, 3]],
      requiredAccuracy: 0.75,
      bpm: 70,
    },
  },

  // ---------------- Module 3: Fingerpicking Technique ----------------
  {
    id: 'l7-pima',
    moduleId: 'technique',
    title: 'Thumb & Fingers (p-i-m-a)',
    category: 'technique',
    summary: 'Assign each finger a string for clean fingerpicking.',
    content: [
      { type: 'paragraph', text: 'Classical fingerstyle labels the picking hand: p = thumb, i = index, m = middle, a = ring. A common ukulele assignment is thumb on the G string, index on C, middle on E, ring on A.' },
      { type: 'paragraph', text: 'Keep your hand relaxed and let each finger pluck its own string. Aim for an even volume across all four.' },
      { type: 'tip', text: 'Anchor lightly with your forearm, not your pinky. Tension is the enemy of clean picking.' },
    ],
    practice: [
      {
        id: 'l7-p1',
        title: 'Thumb & index (G ↔ C)',
        instructions: 'Alternate thumb (G) and index (C) in time.',
        root: 'C',
        scaleKey: 'ionian',
        positions: [[0, 0], [1, 0], [0, 0], [1, 0]],
        bpm: 60,
      },
      {
        id: 'l7-p2',
        title: 'Middle & ring (E ↔ A)',
        instructions: 'Alternate middle (E) and ring (A) in time.',
        root: 'C',
        scaleKey: 'ionian',
        positions: [[2, 0], [3, 0], [2, 0], [3, 0]],
        bpm: 60,
      },
    ],
    checkpoint: {
      title: 'p-i-m-a: pluck G, C, E, A in time',
      instructions: 'With the metronome on, pluck the open strings in order G-C-E-A using thumb, index, middle, ring. Two passes.',
      root: 'C',
      scaleKey: 'ionian',
      positions: [[0, 0], [1, 0], [2, 0], [3, 0], [0, 0], [1, 0], [2, 0], [3, 0]],
      requiredAccuracy: 0.8,
      bpm: 60,
    },
  },
  {
    id: 'l8-roll',
    moduleId: 'technique',
    title: 'The Pinch & Roll',
    category: 'technique',
    summary: 'Sweep across the strings for a harp-like roll.',
    content: [
      { type: 'paragraph', text: 'A "roll" plucks the strings in quick succession, up then back down, creating a rippling arpeggio. It is the foundation of countless fingerstyle blues intros.' },
      { type: 'paragraph', text: 'Roll up G-C-E-A, then back down E-C. Keep the motion smooth and continuous rather than four separate stabs.' },
    ],
    practice: [
      {
        id: 'l8-p1',
        title: 'Ascending roll',
        instructions: 'Smoothly roll up: G, C, E, A.',
        root: 'C',
        scaleKey: 'ionian',
        positions: [[0, 0], [1, 0], [2, 0], [3, 0]],
        bpm: 60,
      },
      {
        id: 'l8-p2',
        title: 'Descending roll',
        instructions: 'Smoothly roll down: A, E, C, G.',
        root: 'C',
        scaleKey: 'ionian',
        positions: [[3, 0], [2, 0], [1, 0], [0, 0]],
        bpm: 60,
      },
    ],
    checkpoint: {
      title: 'Roll up and back down',
      instructions: 'Play the rolling pattern G-C-E-A-E-C in time with the metronome.',
      root: 'C',
      scaleKey: 'ionian',
      positions: [[0, 0], [1, 0], [2, 0], [3, 0], [2, 0], [1, 0]],
      requiredAccuracy: 0.8,
      bpm: 60,
    },
  },
  {
    id: 'l9-travis',
    moduleId: 'technique',
    title: 'Travis Picking: Alternating Bass',
    category: 'technique',
    summary: 'The steady thumb pattern behind fingerstyle blues.',
    content: [
      { type: 'paragraph', text: 'Travis picking keeps a steady alternating bass with the thumb while the fingers add melody on top. On ukulele we approximate it by bouncing the thumb between two lower strings and answering with a higher string.' },
      { type: 'paragraph', text: 'For this checkpoint the thumb alternates G and E while the ring finger answers on A. Keep the bass dead steady — it is the heartbeat of the groove.' },
      { type: 'tip', text: 'Practice the thumb alone first (G, E, G, E), then add the A string answers.' },
    ],
    practice: [
      {
        id: 'l9-p1',
        title: 'Thumb alone (G ↔ E)',
        instructions: 'Practice the alternating bass with the thumb only: G, E, G, E.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[0, 0], [2, 0], [0, 0], [2, 0]],
        bpm: 66,
      },
      {
        id: 'l9-p2',
        title: 'Add the answer',
        instructions: 'Add the A-string answer: G (bass), A, E (bass), A.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[0, 0], [3, 0], [2, 0], [3, 0]],
        bpm: 66,
      },
    ],
    checkpoint: {
      title: 'Alternating bass with answer',
      instructions: 'Play the pattern G(bass)-A(answer)-E(bass)-A(answer), repeated, in time.',
      root: 'C',
      scaleKey: 'mixolydian',
      positions: [[0, 0], [3, 0], [2, 0], [3, 0], [0, 0], [3, 0], [2, 0], [3, 0]],
      requiredAccuracy: 0.8,
      bpm: 66,
    },
  },

  // ---------------- Module 4: Putting It Together ----------------
  {
    id: 'l10-c7-groove',
    moduleId: 'together',
    title: 'Fingerpicked C7 Groove',
    category: 'practice',
    summary: 'Turn the C7 chord into a rolling fingerstyle groove.',
    content: [
      { type: 'paragraph', text: 'Now combine the C7 arpeggio with a rolling motion. You will pick up through the chord tones and back down, outlining the C7 sound one note at a time.' },
      { type: 'paragraph', text: 'Bass C, then up through E-G-Bb, then back down G-E. Keep it smooth and let the b7 (Bb) sing — that is the bluesy color.' },
    ],
    practice: [
      {
        id: 'l10-p1',
        title: 'C7 up',
        instructions: 'Roll up through the chord tones: C, E, G, Bb.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[1, 0], [2, 0], [2, 3], [3, 1]],
        bpm: 70,
      },
      {
        id: 'l10-p2',
        title: 'C7 down',
        instructions: 'Roll back down: Bb, G, E, C.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[3, 1], [2, 3], [2, 0], [1, 0]],
        bpm: 70,
      },
    ],
    checkpoint: {
      title: 'C7 rolling groove',
      instructions: 'Play C-E-G-Bb-G-E in time with the metronome, smoothly rolling up and back.',
      root: 'C',
      scaleKey: 'mixolydian',
      positions: [[1, 0], [2, 0], [2, 3], [3, 1], [2, 3], [2, 0]],
      requiredAccuracy: 0.8,
      bpm: 70,
    },
  },
  {
    id: 'l11-turnaround',
    moduleId: 'together',
    title: 'The Blues Turnaround',
    category: 'practice',
    summary: 'The descending lick that sends the form back to the top.',
    content: [
      { type: 'paragraph', text: 'A turnaround happens in the last two bars of the 12-bar form. It is usually a descending line that builds tension on the V chord and pushes the music back to bar 1.' },
      { type: 'paragraph', text: 'This classic move walks down the A string chromatically — C, B, Bb, A — and lands on G, the root of the V chord. That descending slide is one of the most recognizable sounds in blues.' },
    ],
    practice: [
      {
        id: 'l11-p1',
        title: 'Chromatic walk-down',
        instructions: 'Walk down the A string one fret at a time: C, B, Bb, A.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[3, 3], [3, 2], [3, 1], [3, 0]],
        bpm: 70,
      },
      {
        id: 'l11-p2',
        title: 'Resolve to the V',
        instructions: 'Practice landing on the V chord root: A, then G.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[3, 0], [2, 3]],
        bpm: 70,
      },
    ],
    checkpoint: {
      title: 'Descending turnaround to V',
      instructions: 'Walk down C-B-Bb-A and land on G in time with the metronome.',
      root: 'C',
      scaleKey: 'mixolydian',
      positions: [[3, 3], [3, 2], [3, 1], [3, 0], [2, 3]],
      requiredAccuracy: 0.8,
      bpm: 70,
    },
  },
  {
    id: 'l12-full-chorus',
    moduleId: 'together',
    title: '12-Bar Fingerstyle Blues in C',
    category: 'practice',
    summary: 'Your graduation: a full fingerstyle blues chorus.',
    content: [
      { type: 'paragraph', text: 'This is everything you have learned in one sequence. You will outline the I, IV, and V chords with rolling arpeggios and finish with the turnaround that sends you back to the top.' },
      { type: 'list', items: ['I (C7): C-E-G-Bb', 'IV (F): F-A-C', 'V (G): G-B-D', 'Turnaround: C-B-Bb-A → G'] },
      { type: 'tip', text: 'Take it slow. Passing this checkpoint means you can play a complete fingerstyle blues chorus — the real thing.' },
    ],
    practice: [
      {
        id: 'l12-p1',
        title: 'I–IV–V roots',
        instructions: 'Walk the three chord roots: C, F, G, C.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[1, 0], [2, 1], [2, 3], [1, 0]],
        bpm: 75,
      },
      {
        id: 'l12-p2',
        title: 'C7 & F arpeggios',
        instructions: 'Arpeggiate the I and IV chords: C E G Bb, then F A C.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[1, 0], [2, 0], [2, 3], [3, 1], [2, 1], [3, 0], [3, 3]],
        bpm: 75,
      },
      {
        id: 'l12-p3',
        title: 'The turnaround',
        instructions: 'Finish with the turnaround: C, B, Bb, A, G.',
        root: 'C',
        scaleKey: 'mixolydian',
        positions: [[3, 3], [3, 2], [3, 1], [3, 0], [2, 3]],
        bpm: 75,
      },
    ],
    checkpoint: {
      title: 'Full 12-bar fingerstyle chorus',
      instructions: 'Play the full chorus: C7 arpeggio, F arpeggio, back to C7, then G-F-C with the turnaround. Stay steady with the metronome.',
      root: 'C',
      scaleKey: 'mixolydian',
      positions: [
        // I (C7): C E G Bb
        [1, 0], [2, 0], [2, 3], [3, 1],
        // IV (F): F A C
        [2, 1], [3, 0], [3, 3],
        // back to I (C7): C E G
        [1, 0], [2, 0], [2, 3],
        // V (G) then IV (F): G ... F
        [2, 3], [2, 1],
        // turnaround: C B Bb A -> G
        [3, 3], [3, 2], [3, 1], [3, 0], [2, 3],
      ],
      requiredAccuracy: 0.85,
      bpm: 75,
    },
  },
];

export const bluesCurriculum = createCurriculum({
  id: 'ukulele-fingerpicking-blues',
  title: 'Fingerpicking Blues',
  description: 'A guided path from open strings to a full 12-bar fingerstyle chorus.',
  referenceBoard: generateFretboard(TUNINGS.low_g),
  modules: MODULES,
  lessons: LESSONS,
});

export const {
  resolvePositions,
  getLessonById,
  getLessonIndex,
  getNextLessonId,
  getLessonsForModule,
  isLessonUnlocked,
} = bluesCurriculum;
